// frontend-angular/src/app/chat/chat.component.ts
import { Component } from '@angular/core';
import * as signalR from '@microsoft/signalr';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.css']
})
export class ChatComponent {
  connection!: signalR.HubConnection;
  messages: { text: string; isUser: boolean }[] = [];
  userInput = '';
  connectionId: string | null = null; // Store user's SignalR connection ID

  ngOnInit(): void {
    this.connection = new signalR.HubConnectionBuilder()
      .withUrl('http://localhost:5140/supportHub') // Ensure this URL matches your backend
      .withAutomaticReconnect()
      .build();

    this.startConnection();
  }

  async startConnection(): Promise<void> {
    try {
      await this.connection.start();
      console.log('Connected to SignalR');

      // Get the Connection ID
      this.connectionId = this.connection.connectionId;
      console.log('Connection ID:', this.connectionId);

      this.connection.on('ReceiveMessage', (message: string) => {
        this.addMessage(message, false); // Add bot's response
      });
    } catch (err) {
      console.error('Error while starting connection:', err);
    }
  }

  sendMessage(): void {
    const userInput = this.userInput.trim();
    if (userInput !== '') {
      this.addMessage(userInput, true);
      this.sendMessageToServer(userInput);
      this.userInput = '';
    }
  }

  addMessage(text: string, isUser: boolean): void {
    this.messages.push({ text, isUser });
    this.scrollChatToBottom();
  }

  scrollChatToBottom(): void {
    setTimeout(() => {
      const chatContainer = document.querySelector('.chat-container');
      if (chatContainer) {
        chatContainer.scrollTop = chatContainer.scrollHeight;
      }
    }, 0);
  }

  async sendMessageToServer(message: string): Promise<void> {
    if (!this.connectionId) {
      console.error('No connection ID available. Cannot send message.');
      return;
    }

    try {
      const response = await fetch('http://localhost:5140/api/support/query', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userPrompt: message,
          connectionId: this.connectionId // Pass connection ID to identify user
        })
      });

      if (!response.ok) {
        console.error('Error sending message:', response.statusText);
      }
    } catch (error) {
      console.error('Error sending message:', error);
    }
  }
}

<div class="container">
    <h2 class="text-center mb-4">Technical Support Assistant</h2>
    <div class="chat-container">
      <div *ngFor="let message of messages" [ngClass]="{ 'user-message': message.isUser }" class="message">
        {{ message.text }}
      </div>
    </div>
    <div class="input-group mt-3">
      <input [(ngModel)]="userInput" type="text" class="form-control" placeholder="Type your question here...">
      <button (click)="sendMessage()" class="btn btn-primary">Send</button>
    </div>
  </div>

// frontend-react/src/Chat.js
import React, { useState, useEffect, useRef } from 'react';
import * as signalR from '@microsoft/signalr';

const Chat = () => {
  const [messages, setMessages] = useState([]);
  const [userInput, setUserInput] = useState('');
  const [connectionId, setConnectionId] = useState(null); // Store SignalR connection ID
  const chatContainerRef = useRef(null);
  const connection = useRef(null);

  useEffect(() => {
    connection.current = new signalR.HubConnectionBuilder()
      .withUrl('http://localhost:5140/supportHub') // Ensure this matches your backend
      .withAutomaticReconnect()
      .build();

    connection.current.start()
      .then(() => {
        console.log('Connected to SignalR');
        setConnectionId(connection.current.connectionId); // Store the connection ID
        console.log('Connection ID:', connection.current.connectionId);
      })
      .catch(err => console.error('Error while starting connection:', err));

    connection.current.on('ReceiveMessage', (message) => {
      addMessage(message, false); // Add bot's response
    });

    return () => {
      connection.current.stop();
    };
  }, []);

  const sendMessage = () => {
    const trimmedInput = userInput.trim();
    if (trimmedInput !== '' && connectionId) {
      addMessage(trimmedInput, true);
      sendMessageToServer(trimmedInput);
      setUserInput('');
    }
  };

  const addMessage = (text, isUser) => {
    setMessages(prevMessages => [...prevMessages, { text, isUser }]);
    setTimeout(() => {
      if (chatContainerRef.current) {
        chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
      }
    }, 0);
  };

  const sendMessageToServer = async (message) => {
    if (!connectionId) {
      console.error('No connection ID available. Cannot send message.');
      return;
    }

    try {
      const response = await fetch('http://localhost:5140/api/support/query', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userPrompt: message,
          connectionId: connectionId // Pass connection ID to identify user
        })
      });

      if (!response.ok) {
        console.error('Error sending message:', response.statusText);
      }
    } catch (error) {
      console.error('Error sending message:', error);
    }
  };

  return (
    <div className="container">
      <h2 className="text-center mb-4">Technical Support Assistant</h2>
      <div className="chat-container" ref={chatContainerRef} style={{ maxHeight: '400px', overflowY: 'auto' }}>
        {messages.map((message, index) => (
          <div key={index} className={`message ${message.isUser ? 'user-message' : ''}`}>
            {message.text}
          </div>
        ))}
      </div>
      <div className="input-group mt-3">
        <input
          type="text"
          className="form-control"
          placeholder="Type your question here..."
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
        />
        <button onClick={sendMessage} className="btn btn-primary">Send</button>
      </div>
    </div>
  );
};

export default Chat;
