// frontend-react/src/SupportAdmin.js
import React, { useState } from "react";

const SupportAdminPage = () => {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [message, setMessage] = useState("");

  const addSupportTopic = async () => {
    if (!title.trim() || !description.trim()) {
      setMessage("❌ Please enter both title and description.");
      return;
    }

    const payload = { title, description };

    try {
      const response = await fetch("http://localhost:5140/api/SupportAdmin/add", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }

      const data = await response.json(); // Expecting `{ message: "Success", id: 123 }`
      setMessage(`✅ ${data.message} (ID: ${data.id})`);
      setTitle("");
      setDescription("");
    } catch (error) {
      console.error("Error:", error);
      setMessage("❌ Error adding support topic.");
    }
  };

  return (
    <div className="container mt-4">
      <h2>Add Support Topic</h2>
      <input
        type="text"
        className="form-control my-2"
        placeholder="Title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <textarea
        className="form-control my-2"
        placeholder="Description"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
      />
      <button className="btn btn-primary" onClick={addSupportTopic}>
        Submit
      </button>
      {message && <p className="mt-3">{message}</p>}
    </div>
  );
};

export default SupportAdminPage;

// frontend-angular/src/app/support-admin/support-admin.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { inject } from '@angular/core';

@Component({
  selector: 'app-support-admin',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './support-admin.component.html',
  styleUrls: ['./support-admin.component.css']
})
export class SupportAdminComponent {
  title: string = '';
  description: string = '';
  message: string = '';

  private http = inject(HttpClient);

  addSupportTopic() {
    if (!this.title.trim() || !this.description.trim()) {
      this.message = 'Please enter both title and description.';
      return;
    }

    const payload = {
      title: this.title,
      description: this.description
    };

    // Expect API to return an object with `message` and `id`
    this.http.post<{ message: string; id: number }>('http://localhost:5140/api/SupportAdmin/add', payload)
      .subscribe({
        next: (response) => {
          console.log('API Response:', response); // Debugging
          this.message = `✅ ${response.message} (ID: ${response.id})`;
          this.title = '';
          this.description = '';
        },
        error: (error) => {
          console.error('Error:', error);
          this.message = error.error.message || '❌ Error adding support topic.';
        }
      });
  }
}

<div class="support-form">
    <h2>Add Support Topic</h2>
  
    <label for="title">Title:</label>
    <input id="title" [(ngModel)]="title" placeholder="Enter title" />
  
    <label for="description">Description:</label>
    <textarea id="description" [(ngModel)]="description" placeholder="Enter description"></textarea>
  
    <button (click)="addSupportTopic()">Submit</button>
  
    <p class="message">{{ message }}</p>
  </div>
